[package]
name = "timu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
clap = { version = "4.2.1", features = ["derive"] }
cranelift-codegen = "0.94.0"
miette = "5.7.0"
thiserror = "1.0.40"

# inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm15-0"] }