[package]
name = "libtimu-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full", "parsing"] }
proc-macro2 = "1.0.95"
deluxe = "0.5.0"